name: Check build on linux

on:
  push:
    branches:
      - master
      - dev
      - feature_crossplatform_compilation

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: install libxrandr
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libxrandr-dev

      - uses: actions/checkout@v2

      - name: download submodules
        run: git submodule update --init --recursive

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
